/* 
 * UiBank
 *
 * Sample banking API used for demoing UiPath Testing Automation. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: andrei.barbu@uipath.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CardsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CardsApiTests
    {
        private CardsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CardsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CardsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CardsApi
            //Assert.IsInstanceOfType(typeof(CardsApi), instance, "instance is a CardsApi");
        }

        /// <summary>
        /// Test AddBankCard
        /// </summary>
        [Test]
        public void AddBankCardTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BankCard body = null;
            //long? accountId = null;
            //var response = instance.AddBankCard(body, accountId);
            //Assert.IsInstanceOf<BankCard> (response, "response is BankCard");
        }
        /// <summary>
        /// Test GetCard
        /// </summary>
        [Test]
        public void GetCardTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? cardId = null;
            //var response = instance.GetCard(cardId);
            //Assert.IsInstanceOf<BankCard> (response, "response is BankCard");
        }
        /// <summary>
        /// Test ListBankCards
        /// </summary>
        [Test]
        public void ListBankCardsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? accountId = null;
            //var response = instance.ListBankCards(accountId);
            //Assert.IsInstanceOf<List<BankCard>> (response, "response is List<BankCard>");
        }
    }

}
