# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from app.models.base_model_ import Model
from app import util


class Auth(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, access_token: str=None, token_type: str=None, expires_in: int=None):  # noqa: E501
        """Auth - a model defined in Swagger

        :param access_token: The access_token of this Auth.  # noqa: E501
        :type access_token: str
        :param token_type: The token_type of this Auth.  # noqa: E501
        :type token_type: str
        :param expires_in: The expires_in of this Auth.  # noqa: E501
        :type expires_in: int
        """
        self.swagger_types = {
            'access_token': str,
            'token_type': str,
            'expires_in': int
        }

        self.attribute_map = {
            'access_token': 'access_token',
            'token_type': 'token_type',
            'expires_in': 'expires_in'
        }
        self._access_token = access_token
        self._token_type = token_type
        self._expires_in = expires_in

    @classmethod
    def from_dict(cls, dikt) -> 'Auth':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Auth of this Auth.  # noqa: E501
        :rtype: Auth
        """
        return util.deserialize_model(dikt, cls)

    @property
    def access_token(self) -> str:
        """Gets the access_token of this Auth.


        :return: The access_token of this Auth.
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token: str):
        """Sets the access_token of this Auth.


        :param access_token: The access_token of this Auth.
        :type access_token: str
        """

        self._access_token = access_token

    @property
    def token_type(self) -> str:
        """Gets the token_type of this Auth.


        :return: The token_type of this Auth.
        :rtype: str
        """
        return self._token_type

    @token_type.setter
    def token_type(self, token_type: str):
        """Sets the token_type of this Auth.


        :param token_type: The token_type of this Auth.
        :type token_type: str
        """

        self._token_type = token_type

    @property
    def expires_in(self) -> int:
        """Gets the expires_in of this Auth.


        :return: The expires_in of this Auth.
        :rtype: int
        """
        return self._expires_in

    @expires_in.setter
    def expires_in(self, expires_in: int):
        """Sets the expires_in of this Auth.


        :param expires_in: The expires_in of this Auth.
        :type expires_in: int
        """

        self._expires_in = expires_in
