/* 
 * UiBank
 *
 * Sample banking API used for demoing UiPath Testing Automation. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: andrei.barbu@uipath.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BankCard
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BankCardTests
    {
        // TODO uncomment below to declare an instance variable for BankCard
        //private BankCard instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BankCard
            //instance = new BankCard();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BankCard
        /// </summary>
        [Test]
        public void BankCardInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BankCard
            //Assert.IsInstanceOfType<BankCard> (instance, "variable 'instance' is a BankCard");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DateStart'
        /// </summary>
        [Test]
        public void DateStartTest()
        {
            // TODO unit test for the property 'DateStart'
        }
        /// <summary>
        /// Test the property 'DateEnd'
        /// </summary>
        [Test]
        public void DateEndTest()
        {
            // TODO unit test for the property 'DateEnd'
        }
        /// <summary>
        /// Test the property 'NameOnCard'
        /// </summary>
        [Test]
        public void NameOnCardTest()
        {
            // TODO unit test for the property 'NameOnCard'
        }
        /// <summary>
        /// Test the property 'Pin'
        /// </summary>
        [Test]
        public void PinTest()
        {
            // TODO unit test for the property 'Pin'
        }
        /// <summary>
        /// Test the property 'SecurityCode'
        /// </summary>
        [Test]
        public void SecurityCodeTest()
        {
            // TODO unit test for the property 'SecurityCode'
        }
        /// <summary>
        /// Test the property 'Blocked'
        /// </summary>
        [Test]
        public void BlockedTest()
        {
            // TODO unit test for the property 'Blocked'
        }
        /// <summary>
        /// Test the property 'SelfUrl'
        /// </summary>
        [Test]
        public void SelfUrlTest()
        {
            // TODO unit test for the property 'SelfUrl'
        }
        /// <summary>
        /// Test the property 'AccountUrl'
        /// </summary>
        [Test]
        public void AccountUrlTest()
        {
            // TODO unit test for the property 'AccountUrl'
        }

    }

}
