/* 
 * UiBank
 *
 * Sample banking API used for demoing UiPath Testing Automation. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: andrei.barbu@uipath.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RequestAccount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RequestAccountTests
    {
        // TODO uncomment below to declare an instance variable for RequestAccount
        //private RequestAccount instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RequestAccount
            //instance = new RequestAccount();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RequestAccount
        /// </summary>
        [Test]
        public void RequestAccountInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RequestAccount
            //Assert.IsInstanceOfType<RequestAccount> (instance, "variable 'instance' is a RequestAccount");
        }


        /// <summary>
        /// Test the property 'DateStart'
        /// </summary>
        [Test]
        public void DateStartTest()
        {
            // TODO unit test for the property 'DateStart'
        }
        /// <summary>
        /// Test the property 'FriendlyName'
        /// </summary>
        [Test]
        public void FriendlyNameTest()
        {
            // TODO unit test for the property 'FriendlyName'
        }
        /// <summary>
        /// Test the property 'AccountType'
        /// </summary>
        [Test]
        public void AccountTypeTest()
        {
            // TODO unit test for the property 'AccountType'
        }

    }

}
